name: 'premier_league_dbt'
version: '1.0.0'
config-version: 2

profile: 'default' # links to profiles.yml directly as we name the profile "default"

# where dbt looks for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  premier_league_dbt:
    staging:
      materialized: view
    marts:
      materialized: table