default:
  target: dev
  outputs:
    dev: # for dev env, if has a prod env, add the connection to prod below
      type: postgres
      host: "{{ env_var('POSTGRES_HOST')}}"
      user: "{{ env_var('POSTGRES_USER')}}"
      password: "{{ env_var('POSTGRES_PASSWORD')}}" 
      port: "{{ env_var('POSTGRES_PORT')}}"
      dbname: "{{ env_var('POSTGRES_DB')}}"
      schema: public