services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  airflow:
      build: airflow/ # build from local folder instead of docker hub
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/plugins:/opt/airflow/plugins
        - ./airflow/data_operator:/opt/airflow/data_operator
        - ./airflow/config.py:/opt/airflow/config.py
        - ./.env:/opt/airflow/.env
        - ./data:/opt/airflow/data
        - ./dbt:/opt/airflow/dbt
        - ./metadata:/opt/airflow/metadata
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        DBT_PROFILES_DIR: /opt/airflow/dbt/
        DBT_PROJECT_DIR: /opt/airflow/dbt/
        DATA_DIR: /opt/airflow/data
        METADATA_DIR: /opt/airflow/metadata
      command: webserver
      restart: always
  
  dbt:
    build: dbt/
    depends_on:
      - postgres
    volumes:
      - ./dbt:/opt/dbt
    environment:
      DBT_PROFILES_DIR: /opt/dbt/
      DBT_PROJECT_DIR: /opt/dbt/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    restart: "no" # dbt should only run when triggered by Airflow

  visualization:
    build: visualization/
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      METADATA_DIR: /app/metadata
    volumes:
      - ./metadata:/app/metadata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data: