FROM python:3.12

# WORKDIR /opt

# # Copy requirements
# COPY requirements.txt /opt/requirements.txt

# # Install dependencies
# RUN pip install -r /opt/requirements.txt

# # Copy the application code
# COPY visulazation /opt/visulazation

# EXPOSE 8501
# CMD ["streamlit", "run", "app.py"]